src/models/Login.java

model login

---

src/controllers/IngredienteRegister.java

IngredientRegister.

---

src/controllers/IngredientRegister.java

IngredienteRegister. 0.1

---

src/dao/InputDao.java
src/dao/OutputDao.java
src/dao/RelationSIDao.java
src/dao/RelationSRDao.java
src/dao/RequestDao.java

Dao terminado começando os models

---

src/controllers/IngredienteRegister.java

IngredientRegister 0.2

---

src/ConnectionFactory/EstoqueEditar.java
src/ConnectionFactory/EstoqueEntrada.java
src/ConnectionFactory/FichaEditar.java
src/ConnectionFactory/IngredientController.java
src/ConnectionFactory/IngredienteRegister.java
src/ConnectionFactory/InputController.java
src/ConnectionFactory/JavaEstoqueController.java
src/ConnectionFactory/LoginController.java

Controller 

---

src/dao/IngredientDao.java
src/dao/InputDao.java
src/dao/SnackDao.java

DAO atualizados.

---

src/controllers/SnackController.java
src/controllers/StockController.java

Controller 0.1

---

src/controllers/SnackController.java
src/controllers/StockController.java

Snack - Stock Atualizados.

---

src/controllers/OrdersController.java

OrdersController - 0.0

---

src/controllers/LoginController.java

LoginController = User

---

src/models/User.java

MODEL- USER

---

src/views/SnackAdd.java

Reverts lucassdantas/ProjetoIntegrador#128

Revert "Revert "AddFoto 0.1""

---

src/views/SnackAdd.form
src/views/SnackAdd.java

SnackAdd 0.2

---

src/views/DataSheetAdd.form
src/views/DataSheetAdd.java
src/views/DataSheetEdit.form
src/views/DataSheetEdit.java
src/views/IngredientAdd.form
src/views/IngredientAdd.java
src/views/IngredientEdit.form
src/views/IngredientEdit.java
src/views/InputAdd.form
src/views/InputAdd.java
src/views/InputEdit.form
src/views/InputEdit.java
src/views/PortionCalcResult.form
src/views/PortionCalcResult.java
src/views/SnackAdd.java
src/views/SnackEdit.form
src/views/SnackEdit.java
src/views/StockViews.form
src/views/StockViews.java

Views atualizadas, que não pode colocar letras no lugar de numero.

views atualizadas.

---

src/views/DataSheetAdd.form
src/views/DataSheetAdd.java
src/views/DataSheetEdit.form
src/views/DataSheetEdit.java
src/views/IngredientAdd.form
src/views/IngredientAdd.java
src/views/IngredientEdit.form
src/views/IngredientEdit.java
src/views/InputAdd.form
src/views/InputAdd.java
src/views/InputEdit.form
src/views/InputEdit.java
src/views/PortionCalcResult.form
src/views/PortionCalcResult.java
src/views/SnackAdd.java
src/views/SnackEdit.form
src/views/SnackEdit.java
src/views/StockViews.form
src/views/StockViews.java

Reverts lucassdantas/ProjetoIntegrador#154

Revert "views atualizadas."

---

src/views/DataSheetAdd.form
src/views/DataSheetAdd.java
src/views/DataSheetEdit.form
src/views/DataSheetEdit.java
src/views/IngredientAdd.form
src/views/IngredientAdd.java
src/views/IngredientEdit.form
src/views/IngredientEdit.java
src/views/InputAdd.form
src/views/InputAdd.java
src/views/InputEdit.form
src/views/InputEdit.java
src/views/PortionCalcResult.form
src/views/PortionCalcResult.java
src/views/SnackAdd.java
src/views/SnackEdit.form
src/views/SnackEdit.java
src/views/StockViews.form
src/views/StockViews.java

Atualizado

---

src/views/IngredientAdd.form
src/views/IngredientAdd.java
src/views/IngredientEdit.form
src/views/IngredientEdit.java

Atualização para update e edit das fotos.

Atualização da foto.

---

src/controllers/IngredientController.java

Atualização nos campos "IngredientImageUrl".

Atualização das fotos.

---

src/dao/IngredientDAO.java

Reverts lucassdantas/ProjetoIntegrador#174

Revert "Atualização das fotos."

---

src/views/IngredientAdd.form
src/views/IngredientAdd.java
src/views/IngredientEdit.form
src/views/IngredientEdit.java

Reverts lucassdantas/ProjetoIntegrador#172

Revert "Atualização da foto."
